import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseAnonKey);

const generateId = (prefix) => `${prefix}-${Math.random().toString(36).substr(2, 9)}`;

const properties = [
  {
    id: generateId('prop'),
    title: 'Luxury Villa in Bandra',
    price: 150000000,
    price_display: '₹15 Cr',
    location: 'Bandra West, Mumbai',
    city: 'Mumbai',
    bhk: 4,
    sqft: 3500,
    type: 'Villa',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Luxury Villa in Bandra',
    badge: 'Premium',
    floor: 'Ground + 2',
    furnishing: 'Fully Furnished',
    age: 'New Construction',
    featured: true,
    description: 'Stunning luxury villa with private pool and sea view in the heart of Bandra.',
    amenities: ['Pool', 'Gym', 'Sea View', 'Parking']
  },
  {
    id: generateId('prop'),
    title: 'Modern Apartment in Andheri',
    price: 45000000,
    price_display: '₹4.5 Cr',
    location: 'Andheri West, Mumbai',
    city: 'Mumbai',
    bhk: 3,
    sqft: 1800,
    type: 'Apartment',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Modern Apartment',
    badge: 'Hot Deal',
    floor: '12th Floor',
    furnishing: 'Semi-Furnished',
    age: '2 Years',
    featured: false,
    description: 'Spacious apartment with city views and excellent connectivity.',
    amenities: ['Security', 'Gym', 'Club House', 'Park']
  },
  {
    id: generateId('prop'),
    title: 'Sea Facing Penthouse',
    price: 250000000,
    price_display: '₹25 Cr',
    location: 'Worli, Mumbai',
    city: 'Mumbai',
    bhk: 5,
    sqft: 5000,
    type: 'Penthouse',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Sea Facing Penthouse',
    badge: 'Exclusive',
    floor: '45th Floor',
    furnishing: 'Fully Furnished',
    age: 'New Construction',
    featured: true,
    description: 'Ultra-luxury penthouse offering panoramic views of the Arabian Sea and city skyline.',
    amenities: ['Private Terrace', 'Jacuzzi', 'Concierge', 'Valet']
  },
  {
    id: generateId('prop'),
    title: 'Cozy Studio in Powai',
    price: 40000,
    price_display: '₹40k / month',
    location: 'Powai, Mumbai',
    city: 'Mumbai',
    bhk: 1,
    sqft: 500,
    type: 'Apartment',
    status: 'Rent',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1e5250ce07?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Cozy Studio',
    floor: '5th Floor',
    furnishing: 'Fully Furnished',
    age: '5 Years',
    featured: false,
    description: 'Perfect for bachelors or young couples. Overlooking the Powai lake.',
    amenities: ['Lake View', 'Security', 'Maintenance Staff']
  },
  {
    id: generateId('prop'),
    title: 'Commercial Office Space',
    price: 85000000,
    price_display: '₹8.5 Cr',
    location: 'BKC, Mumbai',
    city: 'Mumbai',
    bhk: 0,
    sqft: 2500,
    type: 'Commercial',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Commercial Office Space',
    badge: 'Investment',
    floor: '8th Floor',
    furnishing: 'Bare Shell',
    age: 'New Construction',
    featured: true,
    description: 'Prime commercial space in the central business district.',
    amenities: ['Central AC', 'Cafeteria', 'Conference Rooms', 'High Speed Elevators']
  },
  {
    id: generateId('prop'),
    title: 'Spacious 2BHK in Thane',
    price: 18000000,
    price_display: '₹1.8 Cr',
    location: 'Ghodbunder Road, Thane',
    city: 'Thane',
    bhk: 2,
    sqft: 1100,
    type: 'Apartment',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Spacious 2BHK',
    floor: '18th Floor',
    furnishing: 'Unfurnished',
    age: 'Under Construction',
    featured: false,
    description: 'Upcoming premium residential complex with world-class amenities.',
    amenities: ['Kids Play Area', 'Swimming Pool', 'Clubhouse']
  },
  {
    id: generateId('prop'),
    title: 'Luxury Independent House',
    price: 120000000,
    price_display: '₹12 Cr',
    location: 'Juhu, Mumbai',
    city: 'Mumbai',
    bhk: 5,
    sqft: 4200,
    type: 'Villa',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Luxury Independent House',
    badge: 'Premium',
    floor: 'Ground + 1',
    furnishing: 'Semi-Furnished',
    age: '10 Years',
    featured: true,
    description: 'Spacious independent house with a private garden in a posh neighborhood.',
    amenities: ['Garden', 'Parking', 'Security']
  },
  {
    id: generateId('prop'),
    title: 'Premium Retail Space',
    price: 150000,
    price_display: '₹1.5L / month',
    location: 'Linking Road, Bandra',
    city: 'Mumbai',
    bhk: 0,
    sqft: 800,
    type: 'Commercial',
    status: 'Rent',
    image: 'https://images.unsplash.com/photo-1555529733-0e670560f4e1?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Premium Retail Space',
    badge: 'Hot Location',
    floor: 'Ground Floor',
    furnishing: 'Furnished',
    age: '15 Years',
    featured: false,
    description: 'Highly visible retail space on a busy shopping street.',
    amenities: ['Main Road Facing', 'Washroom', 'Parking']
  },
  {
    id: generateId('prop'),
    title: 'Quiet Apartment in Navi Mumbai',
    price: 25000000,
    price_display: '₹2.5 Cr',
    location: 'Vashi, Navi Mumbai',
    city: 'Navi Mumbai',
    bhk: 3,
    sqft: 1600,
    type: 'Apartment',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
    image_alt: 'Quiet Apartment',
    floor: '4th Floor',
    furnishing: 'Semi-Furnished',
    age: '8 Years',
    featured: false,
    description: 'Peaceful residential area close to schools and markets.',
    amenities: ['Park', 'Security', 'Intercom']
  },
  {
    id: generateId('prop'),
    title: 'High-Rise Luxury Apartment',
    price: 90000000,
    price_display: '₹9 Cr',
    location: 'Lower Parel, Mumbai',
    city: 'Mumbai',
    bhk: 4,
    sqft: 2800,
    type: 'Apartment',
    status: 'Buy',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    image_alt: 'High-Rise Luxury Apartment',
    badge: 'Exclusive',
    floor: '55th Floor',
    furnishing: 'Fully Furnished',
    age: '3 Years',
    featured: true,
    description: 'Experience luxury living with breathtaking city views.',
    amenities: ['Infinity Pool', 'Gym', 'Spa', 'Mini Theatre']
  }
];

const agents = [
  {
    id: generateId('agent'),
    name: 'Rahul Sharma',
    designation: 'Senior Property Consultant',
    city: 'Mumbai',
    experience: '8 Years',
    speciality: 'Luxury Apartments, Villas',
    properties: 42,
    rating: 4.8,
    reviews: 124,
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Rahul Sharma',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    bio: 'Specializing in luxury real estate across Mumbai with a proven track record.'
  },
  {
    id: generateId('agent'),
    name: 'Priya Desai',
    designation: 'Commercial Real Estate Expert',
    city: 'Mumbai',
    experience: '6 Years',
    speciality: 'Offices, Retail Spaces',
    properties: 28,
    rating: 4.9,
    reviews: 89,
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Priya Desai',
    phone: '+91 98765 12345',
    whatsapp: '+91 98765 12345',
    bio: 'Your go-to expert for commercial investments in BKC and Lower Parel.'
  },
  {
    id: generateId('agent'),
    name: 'Vikram Singh',
    designation: 'Real Estate Broker',
    city: 'Thane',
    experience: '12 Years',
    speciality: 'Residential Apartments',
    properties: 65,
    rating: 4.7,
    reviews: 210,
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Vikram Singh',
    phone: '+91 91234 56789',
    whatsapp: '+91 91234 56789',
    bio: 'Deep knowledge of the Thane and central suburbs market.'
  },
  {
    id: generateId('agent'),
    name: 'Ananya Gupta',
    designation: 'Property Advisor',
    city: 'Navi Mumbai',
    experience: '4 Years',
    speciality: 'New Developments, Plots',
    properties: 18,
    rating: 4.6,
    reviews: 45,
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Ananya Gupta',
    phone: '+91 99887 76655',
    bio: 'Helping families find their dream homes in Navi Mumbai.'
  },
  {
    id: generateId('agent'),
    name: 'Rohan Mehta',
    designation: 'Investment Specialist',
    city: 'Mumbai',
    experience: '10 Years',
    speciality: 'High ROI Properties',
    properties: 34,
    rating: 4.9,
    reviews: 156,
    photo: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Rohan Mehta',
    phone: '+91 98765 54321',
    whatsapp: '+91 98765 54321',
    bio: 'Focused on creating wealth for clients through strategic real estate investments.'
  },
  {
    id: generateId('agent'),
    name: 'Neha Kapoor',
    designation: 'Luxury Homes Specialist',
    city: 'Mumbai',
    experience: '7 Years',
    speciality: 'Sea Facing Apartments',
    properties: 22,
    rating: 4.8,
    reviews: 92,
    photo: 'https://images.unsplash.com/photo-1598550874175-4d0ef43ee90d?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Neha Kapoor',
    phone: '+91 99999 88888',
    whatsapp: '+91 99999 88888',
    bio: 'Connecting elite clients with exclusive sea-facing properties in South Mumbai.'
  },
  {
    id: generateId('agent'),
    name: 'Amit Patel',
    designation: 'Rental Consultant',
    city: 'Mumbai',
    experience: '5 Years',
    speciality: 'Expats, Corporate Leasing',
    properties: 85,
    rating: 4.5,
    reviews: 178,
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Amit Patel',
    phone: '+91 98888 77777',
    bio: 'Making relocation smooth and hassle-free for expats and corporates.'
  },
  {
    id: generateId('agent'),
    name: 'Sneha Reddy',
    designation: 'Real Estate Consultant',
    city: 'Pune',
    experience: '9 Years',
    speciality: 'IT Park Proximities',
    properties: 50,
    rating: 4.7,
    reviews: 134,
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Sneha Reddy',
    phone: '+91 97777 66666',
    whatsapp: '+91 97777 66666',
    bio: 'Expert in residential properties around major IT parks.'
  },
  {
    id: generateId('agent'),
    name: 'Karan Malhotra',
    designation: 'Commercial Broker',
    city: 'Mumbai',
    experience: '15 Years',
    speciality: 'Warehouses, Industrial',
    properties: 40,
    rating: 4.9,
    reviews: 205,
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Karan Malhotra',
    phone: '+91 96666 55555',
    bio: 'Providing comprehensive industrial real estate solutions.'
  },
  {
    id: generateId('agent'),
    name: 'Pooja Joshi',
    designation: 'Property Manager',
    city: 'Thane',
    experience: '3 Years',
    speciality: 'Property Management',
    properties: 120,
    rating: 4.4,
    reviews: 56,
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    photo_alt: 'Pooja Joshi',
    phone: '+91 95555 44444',
    whatsapp: '+91 95555 44444',
    bio: 'Ensuring your investment properties are well-maintained and profitable.'
  }
];

async function seed() {
  console.log('Seeding Properties...');
  const { error: propError } = await supabase.from('properties').insert(properties);
  if (propError) console.error('Error inserting properties:', propError);
  else console.log(`Successfully inserted ${properties.length} properties.`);

  console.log('Seeding Agents...');
  const { error: agentError } = await supabase.from('agents').insert(agents);
  if (agentError) console.error('Error inserting agents:', agentError);
  else console.log(`Successfully inserted ${agents.length} agents.`);
}

seed();
